import type { Piece } from './types';

/**
 * Sample editorial content. It is written rather than dummied, because
 * placeholder text hides whether the typography and hierarchy actually work.
 * Replace before publishing — do not ship any of it as established fact.
 */
export const pieces: Piece[] = [
  /* ── THINK ──────────────────────────────────────────────────────── */
  {
    slug: 'what-we-owe-strangers',
    title: 'What We Owe the People We Will Never Meet',
    question: 'Does a stranger have a claim on my life?',
    pillar: 'think',
    type: 'film',
    seriesSlug: 'life-and-time',
    part: 1,
    date: '2026-07-14',
    dek: 'Every moral tradition draws a circle and puts some people inside it. The interesting question is not where the line falls, but who gets to move it.',
    plate: 'aperture',
    minutes: 14,
    featured: true,
    essay: [
      {
        kind: 'p',
        text: 'You will spend your life among perhaps a few hundred people you actually know. Beyond them are eight billion others whose existence you accept as an abstraction. Almost every ethical system ever written is, at bottom, an argument about where the edge of your obligation sits — and almost none of them agree.',
      },
      {
        kind: 'claim',
        claim: 'fact',
        text: 'Codes of hospitality binding a household to an unknown traveller appear independently in Greek, Vedic, Semitic, Celtic and West African traditions, in societies with no plausible contact between them.',
      },
      {
        kind: 'p',
        text: 'That convergence is striking enough that it demands explanation. The usual one is practical: in a world without inns, police or insurance, a reciprocal duty to shelter strangers is simply good infrastructure. Today I feed you; in a year, on a road far from here, someone feeds me.',
      },
      {
        kind: 'claim',
        claim: 'interpretation',
        text: 'But the texts themselves rarely argue this way. They tend to describe hospitality not as an exchange but as a recognition — the guest is treated as though something larger had arrived with them.',
      },
      {
        kind: 'quote',
        text: 'The guest is not a person you are helping. The guest is a person in front of whom you find out who you are.',
      },
      {
        kind: 'p',
        text: 'This is the part that survives the collapse of the practical argument. We no longer need strangers to shelter us; we have hotels, embassies, insurance. And yet the sense that turning someone away costs us something has not gone anywhere. It is worth asking what that residue is.',
      },
      { kind: 'h', text: 'The circle and its edge' },
      {
        kind: 'p',
        text: 'Consider how the circle actually moves in practice. It does not widen through argument. It widens through proximity — a face, a name, a story told well enough that the abstraction collapses into a person. This is why famine statistics do not move us and one photograph does. It is a documented weakness in our moral equipment, and it is also, possibly, the only mechanism we have.',
      },
      {
        kind: 'claim',
        claim: 'hypothesis',
        text: 'If moral concern expands mainly through vivid particulars rather than through reasoning, then storytelling is not decoration on ethics. It may be the delivery mechanism ethics actually runs on.',
      },
      {
        kind: 'aside',
        text: 'Which would make the deliberate flooding of that channel — with particulars manufactured to move us toward things that do not deserve it — a serious moral problem, and not merely an aesthetic one.',
      },
      {
        kind: 'claim',
        claim: 'question',
        text: 'If your obligation to a stranger is real, is it lessened by distance? And if it is not, how does anyone live?',
      },
      {
        kind: 'p',
        text: 'We do not think this resolves. We think it is the kind of question you are supposed to carry rather than settle — and that a person who has genuinely carried it treats the people in front of them differently. That may be the whole of the practical content.',
      },
    ],
    sources: [
      { text: 'Homer, Odyssey', detail: 'Books I–IV, on xenia and the obligations of the host' },
      { text: 'Taittirīya Upaniṣad', detail: 'I.11 — atithi devo bhava, and its context' },
      { text: 'Peter Singer', detail: '“Famine, Affluence, and Morality”, 1972' },
      { text: 'Paul Slovic', detail: 'On psychic numbing and the collapse of compassion at scale' },
    ],
    relatedIdeas: ['the-long-silence', 'to-serve-what-it-does'],
    relatedShorts: ['short-the-guest', 'short-one-face'],
  },
  {
    slug: 'the-long-silence',
    title: 'The Long Silence',
    question: 'What do we lose when we are never alone?',
    pillar: 'think',
    type: 'essay',
    seriesSlug: 'life-and-time',
    part: 2,
    date: '2026-06-02',
    dek: 'Solitude and loneliness are not the same condition, and a century that has abolished the first has not cured the second.',
    plate: 'threshold',
    minutes: 9,
    essay: [
      {
        kind: 'p',
        text: 'There is a particular quality of thought that only arrives after a long stretch of being unreachable. Not the first hour — the first hour is mostly restlessness. Somewhere past it, something settles, and a person begins to hear what they actually think rather than what they have been repeating.',
      },
      {
        kind: 'claim',
        claim: 'interpretation',
        text: 'Nearly every contemplative tradition builds in an extended, deliberately boring period of withdrawal. The consistency suggests they were protecting access to something that does not arrive quickly.',
      },
      {
        kind: 'p',
        text: 'The modern condition is not that we lack solitude. It is that we have made it almost impossible to enter accidentally. Every interval that used to produce it — the queue, the walk, the wait, the commute, the minutes before sleep — has been filled. Solitude now requires a decision, and decisions are expensive.',
      },
      {
        kind: 'claim',
        claim: 'question',
        text: 'If you have not been bored in a year, what has not had the chance to occur to you?',
      },
    ],
    sources: [
      { text: 'Blaise Pascal', detail: 'Pensées, 139 — on the inability to sit quietly in a room' },
      { text: 'Hannah Arendt', detail: 'The Life of the Mind, on solitude as the two-in-one of thinking' },
    ],
    relatedIdeas: ['the-feed', 'what-we-owe-strangers'],
  },
  {
    slug: 'the-face-we-cannot-see',
    title: 'The Face We Cannot See',
    question: 'What part of you is visible only to other people?',
    pillar: 'think',
    type: 'film',
    seriesSlug: 'inner-beauty',
    part: 1,
    date: '2026-05-19',
    dek: 'You have never seen your own face in motion, in conversation, unaware of being watched. Everyone who loves you has seen almost nothing else.',
    plate: 'threshold',
    minutes: 11,
    featured: true,
    relatedIdeas: ['the-discipline-of-small-things'],
  },
  {
    slug: 'enough',
    title: 'Enough',
    question: 'Where does a person learn when to stop?',
    pillar: 'think',
    type: 'essay',
    date: '2026-04-08',
    dek: 'Contentment is treated as a mood. It may be closer to a skill — and one that no institution in modern life has any interest in teaching.',
    plate: 'horizon',
    minutes: 8,
    relatedIdeas: ['everyone-is-competing'],
  },

  /* ── UNDERSTAND ─────────────────────────────────────────────────── */
  {
    slug: 'before-the-map',
    title: 'Before the Map',
    question: 'What was here before there was a name for it?',
    pillar: 'understand',
    type: 'film',
    seriesSlug: 'history-of-bharat',
    part: 1,
    date: '2026-08-01',
    dek: 'A subcontinent existed for several thousand years before anyone drew a line around it. Reconstructing what it was, without the borrowed vocabulary of nations, is harder than it sounds.',
    plate: 'column',
    minutes: 22,
    featured: true,
    essay: [
      {
        kind: 'p',
        text: 'The difficulty begins with the words. Almost every term available for describing the deep past of the subcontinent — nation, religion, race, empire, even culture — was formalised in nineteenth-century Europe for nineteenth-century European purposes. Using them is not neutral. It imports a set of assumptions about how human groups work, and then finds those assumptions everywhere it looks.',
      },
      {
        kind: 'claim',
        claim: 'fact',
        text: 'The urban settlements of the Indus valley — Mohenjo-daro, Harappa, Dholavira and roughly a thousand identified sites — show standardised weights, fired brick in consistent ratios, and drainage infrastructure, across an area larger than contemporary Egypt and Mesopotamia combined.',
      },
      {
        kind: 'claim',
        claim: 'fact',
        text: 'The Indus script remains undeciphered. There is no agreed reading of any inscription, and no confirmed bilingual text.',
      },
      {
        kind: 'claim',
        claim: 'interpretation',
        text: 'The absence of monumental palaces or unambiguous royal iconography has been read by many archaeologists as evidence of a less centralised political order than its contemporaries. This is a reading of an absence, and absences are the weakest form of evidence.',
      },
      {
        kind: 'claim',
        claim: 'hypothesis',
        text: 'Some scholars propose administrative continuity between Indus urban practice and later South Asian civic forms. The material chain is not established, and the proposal should be treated as open.',
      },
      {
        kind: 'aside',
        text: 'We are marking these distinctions deliberately, and we will keep marking them. The deep history of this region is a place where confident assertion has done a great deal of damage in several directions at once.',
      },
      {
        kind: 'p',
        text: 'What we can say is narrower and, we think, more interesting: a very large number of people organised a very large area for a very long time, and left behind almost no evidence of the thing we have been trained to look for first — a ruler.',
      },
      {
        kind: 'claim',
        claim: 'question',
        text: 'What would we notice about the past if we were not, by habit, looking for kings?',
      },
    ],
    sources: [
      { text: 'Jonathan Mark Kenoyer', detail: 'Ancient Cities of the Indus Valley Civilization' },
      { text: 'Nayanjot Lahiri', detail: 'Finding Forgotten Cities' },
      { text: 'Asko Parpola', detail: 'The Roots of Hinduism — and on the script problem specifically' },
      { text: 'Romila Thapar', detail: 'Early India: From the Origins to AD 1300' },
    ],
    relatedIdeas: ['borders-are-recent'],
    relatedShorts: ['short-undeciphered'],
  },
  {
    slug: 'borders-are-recent',
    title: 'Borders Are Recent',
    question: 'How old is the idea of a country?',
    pillar: 'understand',
    type: 'essay',
    date: '2026-06-21',
    dek: 'For most of human history, power faded outward from a centre rather than stopping at a line. The line is a modern invention, and it changed what people are.',
    plate: 'horizon',
    minutes: 12,
    relatedIdeas: ['before-the-map', 'how-a-village-became-a-market'],
  },
  {
    slug: 'how-a-village-became-a-market',
    title: 'How a Village Became a Market',
    question: 'When did belonging turn into transaction?',
    pillar: 'understand',
    type: 'film',
    date: '2026-03-30',
    dek: 'Obligation, reciprocity and debt were once relationships between people. Watching them become instruments is watching a particular kind of world end.',
    plate: 'river',
    minutes: 19,
  },
  {
    slug: 'the-invention-of-the-working-day',
    title: 'The Invention of the Working Day',
    question: 'Who decided what a day is worth?',
    pillar: 'understand',
    type: 'essay',
    date: '2026-02-11',
    dek: 'The eight-hour day was not discovered. It was fought for, conceded, and then quietly re-engineered into something that never ends.',
    plate: 'orbit',
    minutes: 10,
  },

  /* ── DISCOVER ───────────────────────────────────────────────────── */
  {
    slug: 'reading-the-bhagavatam-slowly',
    title: 'Reading the Bhāgavatam Slowly',
    question: 'What does a text ask of a reader who does not arrive as a believer?',
    pillar: 'discover',
    type: 'film',
    seriesSlug: 'srimad-bhagavatam',
    part: 1,
    date: '2026-07-28',
    dek: 'A text this large can be read as scripture, as literature, as history, or as argument. Most readers choose one and lose the other three.',
    plate: 'manuscript',
    minutes: 26,
    featured: true,
    essay: [
      {
        kind: 'p',
        text: 'There is a way of approaching an old religious text that flatters everyone and teaches nothing: treat it as a storehouse of pleasant sayings, extract the ones that agree with you, and leave. It is done reverently and dismissively in almost equal measure, and both versions come to the same result — the text never gets to say anything the reader did not already believe.',
      },
      {
        kind: 'p',
        text: 'We want to try the harder thing. Read it slowly. Let it be strange. Notice where it is beautiful, where it is difficult, where it contradicts itself, and where it is doing something we would not do.',
      },
      {
        kind: 'claim',
        claim: 'fact',
        text: 'The Bhāgavata Purāṇa runs to roughly eighteen thousand verses across twelve books, and exists in multiple recensions with meaningful textual variation.',
      },
      {
        kind: 'claim',
        claim: 'interpretation',
        text: 'Its structure is recursive — narrators telling of narrators telling of narrators. That framing is not incidental decoration. It appears to be making a claim about how knowledge reaches a person: always through someone, never neat.',
      },
      {
        kind: 'aside',
        text: 'A note on what this series is not. It is not devotional instruction, and it is not a debunking. Both would be easier. We are trying to read a text that a great many people have lived inside, carefully enough that they would recognise it, and honestly enough that someone outside it learns something real.',
      },
      {
        kind: 'claim',
        claim: 'question',
        text: 'Can you take a text seriously without agreeing with it? Most of us have never been shown how.',
      },
    ],
    sources: [
      { text: 'Bhāgavata Purāṇa', detail: 'Canto 1, in the Sanskrit with parallel translations consulted' },
      { text: 'Edwin Bryant', detail: 'Krishna: The Beautiful Legend of God — translation and critical apparatus' },
      { text: 'Wendy Doniger', detail: 'On Purāṇic narrative structure — noted with awareness of the surrounding debate' },
    ],
    relatedIdeas: ['what-the-old-books-argue-about'],
    relatedShorts: ['short-eighteen-thousand'],
  },
  {
    slug: 'the-guest',
    title: 'The Guest',
    question: 'Why did almost every ancient society make hospitality sacred?',
    pillar: 'discover',
    type: 'essay',
    date: '2026-05-05',
    dek: 'Unconnected civilisations independently arrived at the same rule: the stranger at your door is not to be turned away. That convergence needs an explanation.',
    plate: 'threshold',
    minutes: 7,
    relatedIdeas: ['what-we-owe-strangers'],
  },
  {
    slug: 'what-the-old-books-argue-about',
    title: 'What the Old Books Argue About',
    question: 'Where do ancient traditions disagree with themselves?',
    pillar: 'discover',
    type: 'visual',
    date: '2026-01-26',
    dek: 'Traditions are usually presented as settled blocks of agreed belief. Opened up, they are mostly long-running arguments that were never resolved.',
    plate: 'manuscript',
    minutes: 6,
  },

  /* ── QUESTION ───────────────────────────────────────────────────── */
  {
    slug: 'the-exam',
    title: 'The Exam',
    question: 'What is school actually measuring?',
    pillar: 'question',
    type: 'film',
    seriesSlug: 'education-and-competition',
    part: 1,
    date: '2026-08-11',
    dek: 'A system that sorts millions of children each year is worth understanding precisely: what it was built to do, and what it now does instead.',
    plate: 'orbit',
    minutes: 24,
    featured: true,
    essay: [
      {
        kind: 'p',
        text: 'Begin with the least controversial observation available: examinations are a technology. They were designed, by identifiable people, to solve an identifiable problem. They are not a natural feature of learning, and for most of the history of education they did not exist.',
      },
      {
        kind: 'claim',
        claim: 'fact',
        text: 'Competitive written examination as a mechanism for allocating state office was developed in imperial China and formalised over centuries; the British civil service adopted a version of it in the mid-nineteenth century, explicitly citing that precedent.',
      },
      {
        kind: 'claim',
        claim: 'interpretation',
        text: 'The problem it solved was patronage, not pedagogy. An exam is a device for making selection appear impersonal. Whether it measures capability is a separate question from whether it defeats nepotism — and it was adopted to do the second.',
      },
      {
        kind: 'p',
        text: 'This matters because the two purposes have long since come apart. A mechanism built to rank candidates fairly for a limited number of posts has been placed at the centre of childhood, and children are not candidates. They are people in the middle of becoming.',
      },
      {
        kind: 'claim',
        claim: 'hypothesis',
        text: 'When a measure is used to allocate something scarce, effort migrates from the underlying quality to the measure. If that holds in education, then a system optimising examination performance will, over time, produce less of the understanding it was meant to detect.',
      },
      {
        kind: 'aside',
        text: 'We are not arguing for the abolition of assessment. Something has to allocate places, and the alternatives to an exam have historically been worse and less fair. The question is narrower: what does it cost, who pays it, and have we ever actually looked?',
      },
      {
        kind: 'claim',
        claim: 'question',
        text: 'If a child could not be ranked, what would we want them to learn?',
      },
    ],
    sources: [
      { text: 'Benjamin Elman', detail: 'A Cultural History of Civil Examinations in Late Imperial China' },
      { text: 'Northcote–Trevelyan Report', detail: '1854, on reform of the British civil service' },
      { text: 'Donald T. Campbell', detail: 'On the corruption pressure of quantitative social indicators, 1979' },
    ],
    relatedIdeas: ['everyone-is-competing', 'the-feed'],
    relatedShorts: ['short-ranked', 'short-what-if-no-marks'],
  },
  {
    slug: 'everyone-is-competing',
    title: 'Everyone Is Competing. For What?',
    question: 'Who set the finish line?',
    pillar: 'question',
    type: 'essay',
    seriesSlug: 'education-and-competition',
    part: 2,
    date: '2026-07-02',
    dek: 'A race is a reasonable thing to run once you have decided the destination is worth arriving at. Very few people report having made that decision.',
    plate: 'column',
    minutes: 9,
    relatedIdeas: ['enough', 'the-exam'],
  },
  {
    slug: 'the-feed',
    title: 'The Feed',
    question: 'What does an attention market do to a person’s inner life?',
    pillar: 'question',
    type: 'film',
    date: '2026-04-22',
    dek: 'The mechanism is not mysterious and it is not evil. It is an auction, running continuously, in which the thing being sold is the shape of your afternoon.',
    plate: 'orbit',
    minutes: 17,
    relatedIdeas: ['the-long-silence'],
  },
  {
    slug: 'the-price-of-being-cared-for',
    title: 'The Price of Being Cared For',
    question: 'What happens when healing becomes an industry?',
    pillar: 'question',
    type: 'essay',
    date: '2026-02-27',
    dek: 'Medicine has never been better and has rarely felt colder. Both things are true, and they may be connected.',
    plate: 'river',
    minutes: 13,
  },

  /* ── BECOME ─────────────────────────────────────────────────────── */
  {
    slug: 'listen-without-interrupting',
    title: 'Listen Without Interrupting',
    question: 'Can attention be practised, or only intended?',
    pillar: 'become',
    type: 'film',
    seriesSlug: 'today-i-will',
    part: 1,
    date: '2026-08-18',
    dek: 'The smallest possible experiment in becoming a better person: for one conversation, do not prepare your reply while the other person is speaking.',
    plate: 'horizon',
    minutes: 8,
    featured: true,
    essay: [
      {
        kind: 'p',
        text: 'Try it once and the difficulty is immediate. Somewhere in the second sentence, your attention leaves the person in front of you and goes to work assembling a response. From there you are no longer listening. You are waiting.',
      },
      {
        kind: 'claim',
        claim: 'interpretation',
        text: 'Most of what passes for conversation is two people taking turns to wait. This is not a moral failure. It is what attention does when it is not held deliberately.',
      },
      {
        kind: 'p',
        text: 'The practice is small enough to actually do. One conversation. Do not plan the reply. Let the silence after they finish be slightly longer than is comfortable. Notice what you hear in it.',
      },
      {
        kind: 'aside',
        text: 'There is nothing to track and nothing to complete. If you do it once and never again, something still happened once — and the person you did it for noticed, even if they could not name what was different.',
      },
    ],
    relatedIdeas: ['to-serve-what-it-does', 'the-discipline-of-small-things'],
    relatedShorts: ['short-the-pause'],
  },
  {
    slug: 'to-serve-what-it-does',
    title: 'What Service Does to the Server',
    question: 'What happens inside a person who gives time to someone who cannot repay them?',
    pillar: 'become',
    type: 'film',
    seriesSlug: 'to-serve',
    part: 1,
    date: '2026-06-14',
    dek: 'Service is usually discussed from the side of the person receiving it. The more interesting change may happen on the other side.',
    plate: 'river',
    minutes: 16,
  },
  {
    slug: 'the-discipline-of-small-things',
    title: 'The Discipline of Small Things',
    question: 'Is character built in large decisions or small ones?',
    pillar: 'become',
    type: 'essay',
    date: '2026-05-27',
    dek: 'Nobody becomes honest in the moment honesty is expensive. They arrive there having already been honest a thousand times when it was free.',
    plate: 'threshold',
    minutes: 8,
    relatedIdeas: ['listen-without-interrupting'],
  },

  /* ── SHORTS ─────────────────────────────────────────────────────── */
  {
    slug: 'short-the-guest',
    title: 'The Stranger at the Door',
    question: 'Why is the guest sacred?',
    pillar: 'discover',
    type: 'short',
    date: '2026-07-16',
    dek: 'Sixty seconds on a rule that unconnected civilisations all arrived at.',
    plate: 'threshold',
  },
  {
    slug: 'short-one-face',
    title: 'One Face',
    question: 'Why does one photograph move us more than a number?',
    pillar: 'think',
    type: 'short',
    date: '2026-07-19',
    dek: 'On the strange arithmetic of compassion.',
    plate: 'aperture',
  },
  {
    slug: 'short-undeciphered',
    title: 'Still Unread',
    question: 'What does it mean that we cannot read them?',
    pillar: 'understand',
    type: 'short',
    date: '2026-08-04',
    dek: 'A thousand cities, and not one sentence we can understand.',
    plate: 'column',
  },
  {
    slug: 'short-eighteen-thousand',
    title: 'Eighteen Thousand Verses',
    question: 'How do you begin a text this large?',
    pillar: 'discover',
    type: 'short',
    date: '2026-07-30',
    dek: 'On starting slowly, on purpose.',
    plate: 'manuscript',
  },
  {
    slug: 'short-ranked',
    title: 'Ranked',
    question: 'What does fifteen years of being measured do to a person?',
    pillar: 'question',
    type: 'short',
    date: '2026-08-13',
    dek: 'A short on the childhood nobody designed.',
    plate: 'orbit',
  },
  {
    slug: 'short-what-if-no-marks',
    title: 'If There Were No Marks',
    question: 'What would a child learn if nothing was scored?',
    pillar: 'question',
    type: 'short',
    date: '2026-08-15',
    dek: 'A thought experiment in under a minute.',
    plate: 'orbit',
  },
  {
    slug: 'short-the-pause',
    title: 'The Pause',
    question: 'How long can you let a silence run?',
    pillar: 'become',
    type: 'short',
    date: '2026-08-20',
    dek: 'One practice, one conversation, today.',
    plate: 'horizon',
  },
];
